### PR TITLE
sample run application hertzbeat based on oceanbase

### PR DESCRIPTION
**Pull request by tomsun28**
## Summary

sample run application hertzbeat based on oceanbase

### CODE REVIEW

**Comment by whhe** [comment]
Hi @tomsun28, thanks for your contribution!

I found that the module you added has a very detailed instruction, could you please add a CI job to build and start the sample peoject based on it? You can add something like the following to the `.github/workflows/ci.yml`

```yaml
  application-hertzbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Java env
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Start OceanBase container
        uses: oceanbase/setup-oceanbase-ce@v1.0
        with:
          network: 'host'
      - name: Build and start HertzBeat
        run: |
          cd applications/hertzbeat
          mvn clean install
          // TODO start the backend
          cd web-app
          yarn install
          yarn start
```

**Comment by tomsun28** [comment]
hi @whhe the ci has add, please take a look. The ci action is in new file ci-hertzbeat.yml (to add path match), whether it needs to be migrated to ci.yml?

**Comment by whhe** [comment]
> hi @whhe the ci has add, please take a look. The ci action is in new file ci-hertzbeat.yml (to add path match), whether it needs to be migrated to ci.yml?

It's ok to keep it as it is now. I'm just curious about where are the configurations about database connection? Maybe we should add some instructions about it.

**Comment by tomsun28** [comment]
> It's ok to keep it as it is now. I'm just curious about where are the configurations about database connection? Maybe we should add some instructions about it.

hi, this is db connection config for test env `mvn clean test` https://github.com/tomsun28/ob-samples/blob/hz/applications/hertzbeat/manager/src/main/resources/application-test.yml#L22

Here is for local or prod env https://github.com/tomsun28/ob-samples/blob/hz/applications/hertzbeat/manager/src/main/resources/application.yml#L72 

i will update the readme to add some notes.

**Comment by tomsun28** [comment]
updated. PTAL thanks.

**Review by whhe — APPROVED** [review]
LGTM, thanks for your patience.

**Pull request merged**
