### PR TITLE
[feature] add mybatis-plus samples

### PR DESCRIPTION
**Pull request by VampireAchao**
## Summary

This pull request introduces a new MyBatis-Plus OceanBase sample, aiming to enhance the documentation and examples available for developers integrating MyBatis-Plus with OceanBase.

## Solution Description

The solution includes the following key components:

1. **Setup and Configuration**: A detailed setup configuration for integrating MyBatis-Plus with OceanBase, including Maven dependencies and application configuration files.
2. **Initialization Script**: An updated `init.sql` script that not only creates necessary tables but also populates them with initial data for immediate testing and demonstration purposes.
3. **Sample Application**: A small Spring Boot application demonstrating the configuration and use of MyBatis-Plus to perform database operations such as read on the OceanBase database.

### CODE REVIEW

**Comment by caifeizhi** [comment]
Please add new modules in .github/workflows/ci.yml and we can merge it after the new ci job passes; just like :https://github.com/oceanbase/ob-samples/pull/36

**Comment by VampireAchao** [comment]
@caifeizhi Done.

**Comment by whhe** [comment]
Sorry for the late response. The basic CI workflow of this repository is based on a `run.sh` file in every module, so please add it in your newly added directory.

**Comment by whhe** [comment]
Hi @VampireAchao, thank you for your update. The code is overall LGTM, but there is a little problem with the CI workflow. The current basic ci workflow already includes the step of starting a database container by default, so if you want to use testcontainers to manage the database container, you should set `with_oceanbase_container` to false in the ci configuration. You can check it at the readme file in repository root directory, and update it if necessary.

**Comment by VampireAchao** [comment]
Thx again, PTAL 👀

**Review by whhe — APPROVED** [review]
LGTM

**Pull request merged**
