### PR TITLE
[Feat]: Add a demo of MyBatis working with OceanBase.

### PR DESCRIPTION
**Pull request by bruce-pang**
## Summary
This pull request introduces a new MyBatis OceanBase sample, aiming to enhance the documentation and examples available for developers integrating MyBatis with OceanBase.

## Solution Description

**1. Setup and Configuration:** A detailed setup configuration for integrating MyBatis with OceanBase, including Maven dependencies and application configuration files.
**2. Sample Application:** A small application demonstrating the configuration and use of MyBatis to perform database operations such as read on the OceanBase database.

### CODE REVIEW

**Comment by bruce-pang** [comment]
@whhe If there is any problem, I will actively cooperate

**Comment by bruce-pang** [comment]
> @whhe If there is any problem, I will actively cooperate.

**Comment by whhe** [comment]
The `Run sample for mybatis` step outputs `No tests to run.`, please take a look on the executation scripts.

https://github.com/oceanbase/ob-samples/actions/runs/9131143344/job/25128275044?pr=45

**Comment by bruce-pang** [comment]
@whhe ci ci test has passed

**Review by whhe — APPROVED** [review]
LGTM, thanks for your great work!

**Comment by bruce-pang** [comment]
Thx

**Pull request merged**
