### PR TITLE
Add Ruby connection to OceanBase

### PR DESCRIPTION
**Pull request by zhs722**

### CODE REVIEW

**Comment by whhe** [comment]
Thanks for your contribution! Please sign the CLA first.

I updated the master branch and added ruby 3.1 in basic ci workflow, please merge or rebase the master branch and add your module to `.github/workflows/ci.yml`. You can refer to the instructions in readme about basic ci job.

**Comment by whhe** [comment]
Hi @zhs722 , you should add the missing `run.sh` to execute the code.

```
Run cd ruby/mysql2
  cd ruby/mysql[2](https://github.com/oceanbase/ob-samples/actions/runs/9302914511/job/25604151078?pr=59#step:8:2)
  sh run.sh
  shell: /usr/bin/bash -e {0}
sh: 0: cannot open run.sh: No such file
Error: Process completed with exit code 2.
```

**Comment by whhe** [comment]
Maybe you should use localhost in the sample to make the CI pass.

```
Run cd ruby/mysql2
  cd ruby/mysql[2](https://github.com/oceanbase/ob-samples/actions/runs/9303283139/job/25605265789?pr=59#step:8:2)
  sh run.sh
  shell: /usr/bin/bash -e {0}
Building native extensions. This could take a while...
Successfully installed mysql2-0.5.6
1 gem installed
连接到OceanBase数据库失败: Can't connect to MySQL server on '172.[3](https://github.com/oceanbase/ob-samples/actions/runs/9303283139/job/25605265789?pr=59#step:8:3)0.3.244:2881' (110)
```

**Comment by zhs722** [comment]
Submit together after adding other methods

**Pull request closed without merging**
