### PR TITLE
feat: Add a demo of SpringBoot #10

### LINKED ISSUE #10: [Feat.]: Add a demo of SpringBoot
### Check Before Asking

- [X] Please check the issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Description

```markdown
Add a demo for SpringBoot working with OceanBase.
```

### Other Information

Ref: https://www.oceanbase.com/docs/community-observer-cn-10000000000900914

### PR DESCRIPTION
**Pull request by bruce-pang**
## Summary
close #10 

## Solution Description
[README-CN.md](https://github.com/oceanbase/ob-samples/files/15133821/README-CN.md)

### CODE REVIEW

**Comment by caifeizhi** [comment]
Thanks for your contribution @bruce-pang . And, please add new modules in .github/workflows/ci.yml and we can merge it after the new ci job passes; just like :https://github.com/oceanbase/ob-samples/pull/36

**Comment by whhe** [comment]
Thanks for you contribution. 

I noticed that you added a new module with prefix `oceanbase-`, now we require that the name of the new module must be the same as the name of the component used, so please remove the directory prefix and so all modules will be named in the same style.

For the CI part, we require that the `run.sh` can actually be executed in GitHub Action of every one module, so you should configure the datasource in the sample with real connection info. Since we start a database instance by default in the basic ci, you can use the connection info of it, which is 'ip=localhost', 'port=2881', 'username=root@sys' or 'username=root@test' and 'password=' (empty).

**Comment by bruce-pang** [comment]
@whhe Done.

**Comment by whhe** [comment]
> @whhe Done.

I see you updated #40, but it introcudes 3 new modules. Can you separate these files into 3 pull requests? 

Take this pull request for example, you can overwrite the files of current branch with the part of `spring-boot-mysql-jpa` in #40 and update this 'springboot' branch.

Besides, we take the component name as the module name, so here the new module directory should be `spring-data-jpa`. See the latest contribution guide at readme: [English](https://github.com/oceanbase/ob-samples/blob/master/README.md#contribution)  [中文](https://github.com/oceanbase/ob-samples/blob/master/README-CN.md#%E8%B4%A1%E7%8C%AE)

**Comment by bruce-pang** [comment]
@whhe OK, I will split three new PRs and resubmit them, and close the original three PRs.

**Pull request closed without merging**
