### PR TITLE
[Feat]: Add a demo of SpringJDBC

### PR DESCRIPTION
**Pull request by bruce-pang**
## Summary
This pull request introduces a new SpringJDBC OceanBase sample, aiming to enhance the documentation and examples available for developers integrating SpringJDBC with OceanBase.

## Solution Description

1. **Setup and Configuration:** A detailed setup configuration for integrating SpringJDBC with OceanBase, including Maven dependencies and application configuration files.
**2. Sample Application:** A small application demonstrating the configuration and use of SpringJDBC to perform database operations.

### CODE REVIEW

**Comment by bruce-pang** [comment]
@whhe SpringJDBC Demo has been re-developed, please review it.

**Comment by whhe** [comment]
Hi @bruce-pang, it seems that there is something wrong in the GitHub CI job of the newly added module, and maybe you should modify the configurations on database connection.

The ci workflow for pull requests created by new contributors currently needs to be triggered by an admin user, so you can't see the results of the ci job immediately. However, you can see job results in your forked repository https://github.com/bruce-pang/ob-samples/actions. Please try to fix the failure and make it pass, then we can merge it into the main branch.

**Comment by bruce-pang** [comment]
@whhe Done.

**Review by whhe — APPROVED** [review]
LGTM, thanks for your contribution!

**Pull request merged**
