### PR TITLE
[Feat]: add export application based on oceanbase mysql tenant

### PR DESCRIPTION
**Pull request by yyt030**

### CODE REVIEW

**Comment by whhe** [comment]
Is `mydata` an open source project? If so, please add a link to it in the readme. And could you please add a CI job for this application? It can be a simple compilation and startup process. If the execution details are hard to set in CI, you can briefly introduce it in the readme.

**Comment by yyt030** [comment]
This is not an open source project, but an idea that came from the idea that I felt that a lot of OBLD was inappropriate after using obdumper and obloader, to implement a simple fluency tool and be compatible with MysqlDunper. 

I will update the ci in the evening

**Comment by yyt030** [comment]
@whhe pls review it.

**Review by whhe — APPROVED** [review]
Great job! I think this application can be maintained as an independent open source project, as the golang tool ecosystem of OceanBase is not very mature now, it may help a lot for some users. Any way, thank you for your contribution.

**Pull request merged**
